### ISSUE TITLE
URGENT dirac-distribution exception

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/management#44]
Trying to make a new release now (this worked on Tuesday with v32r0 now fails with v32r0p1)

```
$ /dirac-distribution.py -l ILCDIRAC -r $ILCDIRAC_TAG  -C thisrelease.cfg -D ILCDIRACTars
$ cat thisrelease.cfg
DefaultModules = ILCDIRAC
Sources
{
  ILCDIRAC = https://gitlab.cern.ch/CLICdp/iLCDirac/ILCDIRAC.git
}
Releases
{
 v32r0p1
  {
    Modules = ILCDIRAC:v32r0p1
    Depends = DIRAC:v7r2p16
  }
}
```

```
Traceback (most recent call last):
  File "/dirac-create-distribution-tarball.py", line 504, in <module>
    result = create()
  File "/dirac-create-distribution-tarball.py", line 486, in create
    _generateReleaseNotes()
  File "/dirac-create-distribution-tarball.py", line 458, in _generateReleaseNotes
    _generateRSTFile(releaseData, rstFileName, args.version, singleVersion)
  File "/dirac-create-distribution-tarball.py", line 375, in _generateRSTFile
    if parseVersionString(version) > parsedPkgVersion:
TypeError: '>' not supported between instances of 'bool' and 'tuple'
Traceback (most recent call last):
  File "/dirac-distribution.py", line 146, in <module>
    doTheMagic()
  File "/dirac-distribution.py", line 105, in doTheMagic
    createModuleTarballs()
  File "/dirac-distribution.py", line 91, in createModuleTarballs
    raise RuntimeError("Failed creating tarball for module %s. Aborting" % modName)
RuntimeError: Failed creating tarball for module ILCDIRAC. Aborting
```

**Comment by andresailer** [comment]
Ok, mistake was  a bad version in the release notes
```
[Rel-v32r0p1]
```
instead of
```
[v32r0p1]
```
